### ISSUE TITLE
`remove-stale-reports` doesn't seem to work

### ISSUE THREAD

**Issue by lrstanley** [ahmadnassri/action-terraform-report#69]
Utilizing **v3.2.5**, and the following configuration -- looks a little funky because this is a reusable workflow, and we have multiple sets of terraform deployments per repository:

```yaml
# [...]
      - name: terraform-plan
        if: ${{ !inputs.destroy && !inputs.apply }}
        run: |
          terraform -chdir="${{ inputs.deployment_name }}" plan \
            -out terraform.plan \
            -var deployment_name="${{ inputs.deployment_name }}" \
            -var environment="${{ inputs.environment }}" ${{ secrets.terraform_args }}

          terraform -chdir="${{ inputs.deployment_name }}" \
            show -no-color terraform.plan > "${{ github.workspace }}/${{ inputs.deployment_name }}.plan.text"

          terraform -chdir="${{ inputs.deployment_name }}" \
            show -json terraform.plan > "${{ github.workspace }}/${{ inputs.deployment_name }}.plan.json"
      - uses: ahmadnassri/action-terraform-report@54b9349621e8310146a87b8c636b8d5fbab5767e
        if: ${{ github.event_name == 'pull_request' && !inputs.destroy && !inputs.apply }}
        with:
          terraform-text: "${{ github.workspace }}/${{ inputs.deployment_name }}.plan.text"
          terraform-json: "${{ github.workspace }}/${{ inputs.deployment_name }}.plan.json"
          custom-header: ":robot: terraform-plan: ${{ inputs.deployment_name }} (env: ${{ inputs.environment }})"
          show-plan: true
          show-diff: false
          remove-stale-reports: true
# [...]
```

Re-running the action twice results in a duplicate set of comments in the PR, and it doesn't remove the previous comments. Not sure if this is due to [this logic](https://github.com/ahmadnassri/action-terraform-report/blob/master/lib/stale.js#L14) and using a custom header, maybe?

Duplicate comment example:
![image](https://user-images.githubusercontent.com/1847365/222197780-6ab0911a-03e1-48f1-83e2-c62ce0c51004.png)

To also add, the second run doesn't show any warnings/errors/etc about not being able to remove comments. This is the result of the 2nd run that added the 2nd comment:

![image](https://user-images.githubusercontent.com/1847365/222198033-da854714-53d8-424b-9e93-aa8f22e5e75a.png)

Thoughts on what the issue may be? Am I misunderstanding what `remove-stale-reports` is used for?
